# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        node-version: [18]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: 6
    - name: Setup InfluxDB
      uses: influxdata/influxdb-action@v3
      with:
        influxdb_version: 2.0.7
        influxdb_start: true
    - name: Setup InfluxDB use
      run: |
        influx setup \
          --username ci_user \
          --password aaaaaaaaa \
          --org dyne \
          --bucket dyne \
          --retention 24 \
          --token PO2t9KsbqN4j8mDeIXZ2uqvNtmfcUXRRe2umYZxN1tdVFFG6C93zXm4hudc03jhERsW3tdCmke0dVDLVcycTIw== \
          --force
    - name: Debug
      run: |
        ls -al
        influx write -b dyne -o dyne -p s 'weather,host=myHost testField="testData" 1556896326'
    - run: yarn
    - run: yarn add -W zenroom
    - run: yarn build
    - run: yarn test
